### ISSUE TITLE
"Fork me on github" banner overlaps the rightmost buttons

### ISSUE THREAD

**Issue by rubahness** [foone/SierraDeathGenerator#3]
resolution: 2880x1800
browser: FF 52 on OSX

Difficult to click the buttons on the right side of the screen because the fork me on github banner is on a higher layer.  Wind up on the github page, which may be a feature, because then I could log this issue. ¯\_(ツ)_/¯
![sierra-generator-layer-index](https://user-images.githubusercontent.com/10877955/36770728-947ada4a-1c11-11e8-979b-83ec6ac04648.png)

Issue also can affect additional rows at narrower screen sizes.

**Comment by foone** [comment]
Fixed in b3976fa11dca79393a744ad99d7e4ac21ce1ac9b
