### ISSUE TITLE
Images saved as transparent on Chrome

### ISSUE THREAD

**Issue by FooSoft** [foone/SierraDeathGenerator#5]
Images are saved out as entirely transparent on Chrome (but work properly on Firefox).

Repro steps:
1. Open https://foone.github.io/SierraDeathGenerator/#bm
2. Click "Save" icon with default text in the textarea
3. Look at resulting image (attached below)

![bm- somewhere in each level there is someone like me who holds a key_to each exit you must find them](https://user-images.githubusercontent.com/544478/37808338-328bd21e-2e07-11e8-8c68-35146e575838.png)

Expected: image has proper color data.

OS: Fedora 26
Chrome: Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by foone** [comment]
I tried using the same browser+OS, and it worked.
can you try a full refresh? (ctrl-shift-r)
Also try right clicking on the page, going to inspect, and looking at console, and see if there are any error messages.

Also, are you using any ad-blockers? It's possible it's blocking the source images.

**Comment by FooSoft** [comment]
There appears to be something going on specifically on this machine (it does not happen on my laptop which has the same Linux distribution and mostly the same packages). There are no errors in the console and this problem still happens even after I disable all my extensions or even run browser in incognito mode (which also blocks extensions).

I am also pretty stumped about what could be going on here. The images that are downloaded have the correct dimensions but it's almost like the blitting is failing at some point in the process. It is also not related to my network connection in any way since I still have the same problem when tunneling all my traffic through Linode. I've tried doing a full refresh as well.

The other day I upgraded to Fedora 27 (did a full reinstall), and still having the same issue.

**Comment by FooSoft** [comment]
Another interesting problem is that when I snap off a tab (or do any tab manipulation), the image displayed also turns transparent. Video attached... in ZIP archive since GitHub doesn't support video uploads directly it seems...

[bug.zip](https://github.com/foone/SierraDeathGenerator/files/1865803/bug.zip)

**Comment by iokaravas** [comment]
Perhaps `canvas.toDataURL('image/jpeg', 1.0)` would work properly there?
Do we need this to be .png / have transparency?

**Comment by FooSoft** [comment]
Saving via right click menu has the same problems, but everything works fine in firefox. JPEG would not be that great since you have the nasty artifacting that comes with it.

This all being a hardware issue seems plausible, since the tiles on the browser home screen do not render properly either now that I think about it. Maybe something up with this version of NVidia drivers or kernel...

**Comment by FooSoft** [comment]
After several kernel and chrome updates, I checked back on this and it looks like everything is working now. Closing this out as it was just some sort of transient bug.
