### ISSUE TITLE
Games collection variety

### ISSUE THREAD

**Issue by emmakris** [foone/SierraDeathGenerator#9]
Hi Foone, I was thinking if it is possible to add more games like "Zelda", or "Metroid", in general games besides SCI / AGI but from 70s / 80s / 90s period.  
I was wondering because the name of the git/app is SierraDeathGenerator and I don't want to add games that might be far away from the main concept's gamescale.

Thank you in advance,
Manolis

**Comment by foone** [comment]
That's perfectly fine. The title is just an artifact at this point. Pretty much anything games-related is fine.
Thanks for asking!

**Comment by emmakris** [comment]
Cool! Thanks Foone I am adding a new one now :)
